#!/bin/bash

if [ $UID -ne 0 ]; then
	echo "Only for root!"
	exit 1
fi

FILE=/pub/titkarsag/ifa-jelszo.csv

su -c "psql iskola -A -q -t -F ';' -c 'select * from fogado_diak_kati'" szaszi | recode u8..l2/crlf > $FILE
chmod 660 $FILE
chown adam:iroda $FILE

