#!/bin/bash

# Összehasonlítja az iskolai adatbázis aktuális névsorát
# az ifa.db névsorával.

BASE=$PWD
TMP=$( mktemp -d )
cd $TMP
DB=/var/ifa/ifa.db

$BASE/local.gen
/var/ifa/gen/gen-db.php local.sql
echo .dump | sqlite3 ifa.db | sort > dump-db

echo .dump | sqlite3 $DB | egrep -v '(Ulog|Fogado|BEGIN|END|id_seq)' | sort > dump-ifa

(
echo '--- NYERS ADAT---------------------------------------------'
diff dump-db dump-ifa
echo
echo '--- Tanar -------------------------------------------------'
echo 'PRAGMA foreign_keys=ON;'
diff dump-db dump-ifa | grep '> INSERT INTO "Tanar" '
diff dump-db dump-ifa | grep '> INSERT INTO "Tanar" ' | sed "s/^[^(]*(\([^,]*\),.*/DELETE FROM \"Tanar\" WHERE id='\1';/"
diff dump-db dump-ifa | grep '< INSERT INTO "Tanar" ' | cut -c3-
echo '--- Diak --------------------------------------------------'
echo 'PRAGMA foreign_keys=ON;'
diff dump-db dump-ifa | grep '> INSERT INTO "Diak_base" '
diff dump-db dump-ifa | grep '> INSERT INTO "Diak_base" ' | sed "s/^[^(]*(\([^,]*\),.*/DELETE FROM \"Diak_base\" WHERE id='\1';/"
diff dump-db dump-ifa | grep '< INSERT INTO "Diak_base" ' | cut -c3-
) | egrep -v '^([0-9]|[<>] (BEGIN|CREATE))' | less -r

cd $BASE

rm -r $TMP

